const {
  ALLOWED_ROLES,
  getAllUsers,
  getUserById,
  getUserByFirebaseUid,
  createUser,
  updateUserById,
  updateUserAvailability,
} = require("../models/userModel");

function isValidUUID(value) {
  const uuidRegex =
    /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
  return uuidRegex.test(value);
}

function parseBoolean(value) {
  if (typeof value === "boolean") {
    return value;
  }

  if (typeof value === "string") {
    const normalized = value.trim().toLowerCase();
    if (normalized === "true") {
      return true;
    }
    if (normalized === "false") {
      return false;
    }
  }

  return null;
}

function handleDatabaseError(error, res) {
  if (error.code === "23505") {
    return res.status(409).json({
      message:
        "Duplicate value violates a unique constraint. roll_no must be unique.",
    });
  }

  return res.status(500).json({ message: "Internal server error" });
}

async function getUsers(req, res) {
  try {
    const { role, availability } = req.query;

    if (role && !ALLOWED_ROLES.includes(role)) {
      return res.status(400).json({
        message: `Invalid role. Allowed roles: ${ALLOWED_ROLES.join(", ")}`,
      });
    }

    let isAvailable;
    if (typeof availability !== "undefined") {
      isAvailable = parseBoolean(availability);
      if (isAvailable === null) {
        return res.status(400).json({
          message: "Invalid availability filter. Use true or false.",
        });
      }
    }

    const users = await getAllUsers({ role, isAvailable });
    return res.status(200).json(users);
  } catch (error) {
    return handleDatabaseError(error, res);
  }
}

async function getUser(req, res) {
  try {
    const { id } = req.params;

    if (!isValidUUID(id)) {
      return res.status(400).json({ message: "Invalid user id format" });
    }

    const user = await getUserById(id);

    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    return res.status(200).json(user);
  } catch (error) {
    return handleDatabaseError(error, res);
  }
}

async function createUserHandler(req, res) {
  try {
    const { name, role } = req.body;

    if (Object.prototype.hasOwnProperty.call(req.body, "id")) {
      return res.status(400).json({
        message: "id must not be provided. It is auto-generated by the system.",
      });
    }

    const firebase_uid = req.user?.uid;
    const email = req.user?.email || req.body.email;

    if (!name || !role) {
      return res.status(400).json({
        message: "Missing required fields: name and role are required.",
      });
    }

    if (!ALLOWED_ROLES.includes(role)) {
      return res.status(400).json({
        message: `Invalid role. Allowed roles: ${ALLOWED_ROLES.join(", ")}`,
      });
    }

    if (
      Object.prototype.hasOwnProperty.call(req.body, "is_available") &&
      typeof req.body.is_available !== "boolean"
    ) {
      return res.status(400).json({
        message: "is_available must be a boolean when provided.",
      });
    }

    const payload = {
      ...req.body,
      firebase_uid,
      email,
    };

    const created = await createUser(payload);
    return res.status(201).json(created);
  } catch (error) {
    return handleDatabaseError(error, res);
  }
}

async function patchUser(req, res) {
  try {
    const { id } = req.params;

    if (!isValidUUID(id)) {
      return res.status(400).json({ message: "Invalid user id format" });
    }

    const allowedFields = [
      "name",
      "roll_no",
      "class_branch",
      "role",
      "skill_level",
      "is_available",
    ];

    const updates = {};
    for (const key of allowedFields) {
      if (Object.prototype.hasOwnProperty.call(req.body, key)) {
        updates[key] = req.body[key];
      }
    }

    if (!Object.keys(updates).length) {
      return res
        .status(400)
        .json({ message: "No valid fields provided for update." });
    }

    if (
      Object.prototype.hasOwnProperty.call(updates, "role") &&
      !ALLOWED_ROLES.includes(updates.role)
    ) {
      return res.status(400).json({
        message: `Invalid role. Allowed roles: ${ALLOWED_ROLES.join(", ")}`,
      });
    }

    if (
      Object.prototype.hasOwnProperty.call(updates, "is_available") &&
      typeof updates.is_available !== "boolean"
    ) {
      return res.status(400).json({
        message: "is_available must be a boolean when provided.",
      });
    }

    const updated = await updateUserById(id, updates);

    if (!updated) {
      return res.status(404).json({ message: "User not found" });
    }

    return res.status(200).json(updated);
  } catch (error) {
    return handleDatabaseError(error, res);
  }
}

async function patchUserAvailability(req, res) {
  try {
    const { id } = req.params;
    const parsedAvailability = parseBoolean(req.body.is_available);

    if (!isValidUUID(id)) {
      return res.status(400).json({ message: "Invalid user id format" });
    }

    if (parsedAvailability === null) {
      return res
        .status(400)
        .json({ message: "is_available is required and must be a boolean." });
    }

    const updated = await updateUserAvailability(id, parsedAvailability);

    if (!updated) {
      return res.status(404).json({ message: "User not found" });
    }

    return res.status(200).json(updated);
  } catch (error) {
    return handleDatabaseError(error, res);
  }
}

async function getCurrentUser(req, res) {
  try {
    const uid = req.user?.uid;
    if (!uid) return res.status(401).json({ message: "No firebase user found" });

    const user = await getUserByFirebaseUid(uid);
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    return res.status(200).json(user);
  } catch (error) {
    return handleDatabaseError(error, res);
  }
}

module.exports = {
  getUsers,
  getUser,
  getCurrentUser,
  createUserHandler,
  patchUser,
  patchUserAvailability,
};
